# Define the name of the GitHub Action workflow
name: CI Backend

# Trigger the workflow on pull requests to the 'develop' branch
on:
  pull_request:
    branches:
      - develop
    # Only trigger when changes are made within the 'data/' directory
    paths:
      - 'backend/**'

# Define default settings for jobs
defaults:
  run:
    working-directory: ./backend

jobs:
  ci:
    runs-on: ubuntu-latest # Run on the latest version of Ubuntu

    # Define the steps to be executed within the job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2 # Check out the repository code

      - name: Set Up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21.1 # GO lastest version

      - name: Install Dependencies
        run: go mod download

      - name: Build Backend
        run: go build -o backend ./path-to-backend

      - name: Install golint
        run: go install golang.org/x/lint/golint@latest

      - name: Run golint # Linter
        run: golint ./path-to-backend

      - name: Run Unit Tests # Unit Test
        run: go test ./path-to-backend
